version: "3.5"

services:
  db:
    image: postgres
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_DB=cash_flow
    ports:
        - "5432:5432"
  web:
    build:
      dockerfile: Dockerfile
    image: entry:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"


